"""Built-in diagnosis templates (spec 6).

Each template declares:
  * ``metrics``            — which indicators are tracked and how each chart is
                             configured (unit, target range, critical thresholds);
  * ``checkin_questions``  — what the patient is asked and how often;
  * ``keywords``           — trilingual matching keys for automatic selection;
  * ``protocol_slugs``     — which approved protocols the AI may answer from.

Target ranges follow common outpatient guidance for adults and are the starting
point a doctor is expected to adjust per patient — they are defaults, not
prescriptions.
"""

from __future__ import annotations

from typing import Any, Final

TEMPLATES: Final[list[dict[str, Any]]] = [
    {
        "code": "diabetes_t2",
        "name": {
            "uz": "Qandli diabet (2-tur)",
            "ru": "Сахарный диабет (2 тип)",
            "en": "Type 2 diabetes",
        },
        "description": {
            "uz": "Qon shakari va HbA1c kuzatuvi, dori intizomi nazorati.",
            "ru": "Контроль глюкозы крови и HbA1c, дисциплина приёма препаратов.",
            "en": "Blood glucose and HbA1c tracking with medication adherence.",
        },
        "specialty": "endocrinologist",
        "icd10": "E11",
        "sort_order": 10,
        "keywords": [
            "qandli diabet",
            "qandli diabet 2",
            "2-tur diabet",
            "diabet",
            "shakar kasalligi",
            "сахарный диабет",
            "диабет 2 типа",
            "диабет",
            "type 2 diabetes",
            "diabetes mellitus",
            "diabetes",
            "t2dm",
        ],
        "metrics": [
            {
                "key": "blood_glucose",
                "label": {
                    "uz": "Qand darajasi",
                    "ru": "Уровень глюкозы",
                    "en": "Blood glucose",
                },
                "unit": "mmol/L",
                "value_type": "number",
                "target_min": 4.4,
                "target_max": 7.2,
                "critical_min": 3.0,
                "critical_max": 13.9,
                "decimals": 1,
                "chart_type": "line",
                "sort_order": 0,
            },
            {
                "key": "hba1c",
                "label": {"uz": "HbA1c", "ru": "HbA1c", "en": "HbA1c"},
                "unit": "%",
                "value_type": "number",
                "target_min": 4.0,
                "target_max": 7.0,
                "critical_min": None,
                "critical_max": 9.0,
                "decimals": 1,
                "chart_type": "line",
                "sort_order": 1,
            },
            {
                "key": "weight",
                "label": {"uz": "Vazn", "ru": "Вес", "en": "Weight"},
                "unit": "kg",
                "value_type": "number",
                "target_min": None,
                "target_max": None,
                "decimals": 1,
                "chart_type": "line",
                "sort_order": 2,
            },
        ],
        "checkin_questions": [
            {
                "key": "glucose_morning",
                "metric_key": "blood_glucose",
                "prompt": {
                    "uz": "Ertalabki qand darajangiz qancha?",
                    "ru": "Какой у вас утренний уровень глюкозы?",
                    "en": "What is your morning blood glucose?",
                },
                "type": "number",
                "unit": "mmol/L",
                "frequency": "daily",
                "times_per_day": 1,
                "slots": ["morning"],
                "required": True,
            },
            {
                "key": "glucose_evening",
                "metric_key": "blood_glucose",
                "prompt": {
                    "uz": "Kechki qand darajangiz qancha?",
                    "ru": "Какой у вас вечерний уровень глюкозы?",
                    "en": "What is your evening blood glucose?",
                },
                "type": "number",
                "unit": "mmol/L",
                "frequency": "daily",
                "times_per_day": 1,
                "slots": ["evening"],
                "required": False,
            },
            {
                "key": "wellbeing",
                "prompt": {
                    "uz": "Bugungi holatingiz qanday?",
                    "ru": "Как вы себя чувствуете сегодня?",
                    "en": "How do you feel today?",
                },
                "type": "choice",
                "options": [
                    {"value": "good", "label": {"uz": "Yaxshi", "ru": "Хорошо", "en": "Good"}},
                    {
                        "value": "normal",
                        "label": {"uz": "O'rtacha", "ru": "Нормально", "en": "Okay"},
                    },
                    {"value": "bad", "label": {"uz": "Yomon", "ru": "Плохо", "en": "Poor"}},
                ],
                "frequency": "daily",
                "slots": ["day"],
                "required": True,
            },
        ],
        "protocol_slugs": ["diabetes_self_care", "hypoglycemia_red_flags", "general_safety"],
    },
    {
        "code": "hypertension",
        "name": {
            "uz": "Arterial gipertoniya",
            "ru": "Артериальная гипертензия",
            "en": "Hypertension",
        },
        "description": {
            "uz": "Qon bosimi va puls kuzatuvi.",
            "ru": "Контроль артериального давления и пульса.",
            "en": "Blood pressure and pulse monitoring.",
        },
        "specialty": "cardiologist",
        "icd10": "I10",
        "sort_order": 20,
        "keywords": [
            "gipertoniya",
            "arterial gipertoniya",
            "qon bosimi",
            "yuqori bosim",
            "gipertenziya",
            "гипертония",
            "артериальная гипертензия",
            "повышенное давление",
            "hypertension",
            "high blood pressure",
        ],
        "metrics": [
            {
                "key": "blood_pressure",
                "label": {
                    "uz": "Qon bosimi",
                    "ru": "Артериальное давление",
                    "en": "Blood pressure",
                },
                "unit": "mmHg",
                # Systolic in `value`, diastolic in `value_secondary`.
                "value_type": "pair",
                "target_min": 90.0,
                "target_max": 135.0,
                "critical_min": 85.0,
                "critical_max": 180.0,
                "decimals": 0,
                "chart_type": "range",
                "sort_order": 0,
            },
            {
                "key": "pulse",
                "label": {"uz": "Puls", "ru": "Пульс", "en": "Pulse"},
                "unit": "bpm",
                "value_type": "number",
                "target_min": 55.0,
                "target_max": 90.0,
                "critical_min": 45.0,
                "critical_max": 120.0,
                "decimals": 0,
                "chart_type": "line",
                "sort_order": 1,
            },
            {
                "key": "weight",
                "label": {"uz": "Vazn", "ru": "Вес", "en": "Weight"},
                "unit": "kg",
                "value_type": "number",
                "decimals": 1,
                "chart_type": "line",
                "sort_order": 2,
            },
        ],
        "checkin_questions": [
            {
                "key": "bp_morning",
                "metric_key": "blood_pressure",
                "prompt": {
                    "uz": "Ertalabki qon bosimingiz qancha?",
                    "ru": "Какое у вас утреннее давление?",
                    "en": "What is your morning blood pressure?",
                },
                "type": "pair",
                "unit": "mmHg",
                "frequency": "daily",
                "times_per_day": 1,
                "slots": ["morning"],
                "required": True,
            },
            {
                "key": "bp_evening",
                "metric_key": "blood_pressure",
                "prompt": {
                    "uz": "Kechki qon bosimingiz qancha?",
                    "ru": "Какое у вас вечернее давление?",
                    "en": "What is your evening blood pressure?",
                },
                "type": "pair",
                "unit": "mmHg",
                "frequency": "daily",
                "times_per_day": 1,
                "slots": ["evening"],
                "required": False,
            },
            {
                "key": "headache",
                "prompt": {
                    "uz": "Bosh og'rig'i bormi?",
                    "ru": "Есть ли головная боль?",
                    "en": "Do you have a headache?",
                },
                "type": "boolean",
                "frequency": "daily",
                "slots": ["day"],
                "required": True,
            },
        ],
        "protocol_slugs": ["hypertension_self_care", "cardiac_red_flags", "general_safety"],
    },
    {
        "code": "asthma",
        "name": {"uz": "Bronxial astma", "ru": "Бронхиальная астма", "en": "Asthma"},
        "description": {
            "uz": "Nafas ko'rsatkichlari va xurujlar kuzatuvi.",
            "ru": "Контроль показателей дыхания и приступов.",
            "en": "Respiratory readings and attack tracking.",
        },
        "specialty": "pulmonologist",
        "icd10": "J45",
        "sort_order": 30,
        "keywords": [
            "astma",
            "bronxial astma",
            "nafas qisishi",
            "бронхиальная астма",
            "астма",
            "asthma",
        ],
        "metrics": [
            {
                "key": "peak_flow",
                "label": {
                    "uz": "Cho'qqi oqim (PEF)",
                    "ru": "Пиковая скорость (PEF)",
                    "en": "Peak flow (PEF)",
                },
                "unit": "L/min",
                "value_type": "number",
                "target_min": 300.0,
                "target_max": 700.0,
                "critical_min": 200.0,
                "critical_max": None,
                "decimals": 0,
                "chart_type": "line",
                "sort_order": 0,
            },
            {
                "key": "spo2",
                "label": {"uz": "SpO₂", "ru": "SpO₂", "en": "SpO₂"},
                "unit": "%",
                "value_type": "number",
                "target_min": 95.0,
                "target_max": 100.0,
                "critical_min": 92.0,
                "critical_max": None,
                "decimals": 0,
                "chart_type": "line",
                "sort_order": 1,
            },
            {
                "key": "inhaler_uses",
                "label": {
                    "uz": "Ingalyator ishlatilishi",
                    "ru": "Использование ингалятора",
                    "en": "Reliever inhaler uses",
                },
                "unit": "marta",
                "value_type": "number",
                "target_min": 0.0,
                "target_max": 2.0,
                "critical_max": 8.0,
                "decimals": 0,
                "chart_type": "bar",
                "sort_order": 2,
            },
        ],
        "checkin_questions": [
            {
                "key": "peak_flow_daily",
                "metric_key": "peak_flow",
                "prompt": {
                    "uz": "Cho'qqi oqim ko'rsatkichingiz qancha?",
                    "ru": "Какова ваша пиковая скорость выдоха?",
                    "en": "What is your peak flow reading?",
                },
                "type": "number",
                "unit": "L/min",
                "frequency": "daily",
                "slots": ["morning"],
                "required": True,
            },
            {
                "key": "night_symptoms",
                "prompt": {
                    "uz": "Kecha tunda nafas qisishi bezovta qildimi?",
                    "ru": "Беспокоила ли одышка прошлой ночью?",
                    "en": "Did breathlessness disturb you last night?",
                },
                "type": "boolean",
                "frequency": "daily",
                "slots": ["day"],
                "required": True,
            },
        ],
        "protocol_slugs": ["asthma_self_care", "respiratory_red_flags", "general_safety"],
    },
    {
        "code": "ckd",
        "name": {
            "uz": "Surunkali buyrak kasalligi",
            "ru": "Хроническая болезнь почек",
            "en": "Chronic kidney disease",
        },
        "description": {
            "uz": "Kreatinin, bosim va suyuqlik balansi kuzatuvi.",
            "ru": "Контроль креатинина, давления и водного баланса.",
            "en": "Creatinine, blood pressure and fluid balance tracking.",
        },
        "specialty": "nephrologist",
        "icd10": "N18",
        "sort_order": 40,
        "keywords": [
            "buyrak kasalligi",
            "surunkali buyrak",
            "buyrak yetishmovchiligi",
            "хроническая болезнь почек",
            "почечная недостаточность",
            "chronic kidney disease",
            "ckd",
        ],
        "metrics": [
            {
                "key": "creatinine",
                "label": {"uz": "Kreatinin", "ru": "Креатинин", "en": "Creatinine"},
                "unit": "µmol/L",
                "value_type": "number",
                "target_min": 60.0,
                "target_max": 110.0,
                "critical_max": 300.0,
                "decimals": 0,
                "chart_type": "line",
                "sort_order": 0,
            },
            {
                "key": "blood_pressure",
                "label": {
                    "uz": "Qon bosimi",
                    "ru": "Артериальное давление",
                    "en": "Blood pressure",
                },
                "unit": "mmHg",
                "value_type": "pair",
                "target_min": 90.0,
                "target_max": 130.0,
                "critical_max": 180.0,
                "decimals": 0,
                "chart_type": "range",
                "sort_order": 1,
            },
            {
                "key": "weight",
                "label": {"uz": "Vazn", "ru": "Вес", "en": "Weight"},
                "unit": "kg",
                "value_type": "number",
                "decimals": 1,
                "chart_type": "line",
                "sort_order": 2,
            },
        ],
        "checkin_questions": [
            {
                "key": "swelling",
                "prompt": {
                    "uz": "Oyoqlarda shish bormi?",
                    "ru": "Есть ли отёки на ногах?",
                    "en": "Do you have swelling in your legs?",
                },
                "type": "boolean",
                "frequency": "daily",
                "slots": ["day"],
                "required": True,
            },
            {
                "key": "weight_daily",
                "metric_key": "weight",
                "prompt": {
                    "uz": "Bugungi vazningiz qancha?",
                    "ru": "Каков ваш вес сегодня?",
                    "en": "What is your weight today?",
                },
                "type": "number",
                "unit": "kg",
                "frequency": "daily",
                "slots": ["morning"],
                "required": True,
            },
        ],
        "protocol_slugs": ["ckd_self_care", "general_safety"],
    },
    {
        "code": "hypothyroidism",
        "name": {"uz": "Gipotireoz", "ru": "Гипотиреоз", "en": "Hypothyroidism"},
        "description": {
            "uz": "TTG kuzatuvi va dori intizomi.",
            "ru": "Контроль ТТГ и приверженность лечению.",
            "en": "TSH monitoring and medication adherence.",
        },
        "specialty": "endocrinologist",
        "icd10": "E03",
        "sort_order": 50,
        "keywords": [
            "gipotireoz",
            "qalqonsimon bez",
            "tireoid",
            "гипотиреоз",
            "щитовидная железа",
            "hypothyroidism",
            "thyroid",
        ],
        "metrics": [
            {
                "key": "tsh",
                "label": {"uz": "TTG (TSH)", "ru": "ТТГ", "en": "TSH"},
                "unit": "mIU/L",
                "value_type": "number",
                "target_min": 0.4,
                "target_max": 4.0,
                "critical_max": 10.0,
                "decimals": 2,
                "chart_type": "line",
                "sort_order": 0,
            },
            {
                "key": "weight",
                "label": {"uz": "Vazn", "ru": "Вес", "en": "Weight"},
                "unit": "kg",
                "value_type": "number",
                "decimals": 1,
                "chart_type": "line",
                "sort_order": 1,
            },
        ],
        "checkin_questions": [
            {
                "key": "fatigue",
                "prompt": {
                    "uz": "Holsizlik sezyapsizmi?",
                    "ru": "Чувствуете ли слабость?",
                    "en": "Are you feeling fatigued?",
                },
                "type": "choice",
                "options": [
                    {"value": "no", "label": {"uz": "Yo'q", "ru": "Нет", "en": "No"}},
                    {
                        "value": "mild",
                        "label": {"uz": "Yengil", "ru": "Лёгкая", "en": "Mild"},
                    },
                    {
                        "value": "strong",
                        "label": {"uz": "Kuchli", "ru": "Сильная", "en": "Strong"},
                    },
                ],
                "frequency": "weekly",
                "slots": ["day"],
                "required": False,
            }
        ],
        "protocol_slugs": ["thyroid_self_care", "general_safety"],
    },
    {
        "code": "general_monitoring",
        "name": {
            "uz": "Umumiy kuzatuv",
            "ru": "Общее наблюдение",
            "en": "General monitoring",
        },
        "description": {
            "uz": "Maxsus shablon topilmaganda ishlatiladigan asosiy kuzatuv.",
            "ru": "Базовое наблюдение, когда специальный шаблон не найден.",
            "en": "Baseline monitoring used when no specific template matches.",
        },
        "specialty": "therapist",
        "sort_order": 900,
        # No keywords: this template is a deliberate fallback, chosen explicitly
        # by the doctor rather than auto-matched.
        "keywords": [],
        "metrics": [
            {
                "key": "wellbeing_score",
                "label": {"uz": "Umumiy holat", "ru": "Общее состояние", "en": "Wellbeing"},
                "unit": "ball",
                "value_type": "number",
                "target_min": 6.0,
                "target_max": 10.0,
                "critical_min": 3.0,
                "decimals": 0,
                "chart_type": "line",
                "sort_order": 0,
            },
            {
                "key": "temperature",
                "label": {"uz": "Harorat", "ru": "Температура", "en": "Temperature"},
                "unit": "°C",
                "value_type": "number",
                "target_min": 36.0,
                "target_max": 37.2,
                "critical_max": 38.5,
                "decimals": 1,
                "chart_type": "line",
                "sort_order": 1,
            },
        ],
        "checkin_questions": [
            {
                "key": "wellbeing_today",
                "metric_key": "wellbeing_score",
                "prompt": {
                    "uz": "Bugungi holatingizni 1-10 ball bilan baholang",
                    "ru": "Оцените ваше состояние сегодня от 1 до 10",
                    "en": "Rate how you feel today from 1 to 10",
                },
                "type": "number",
                "unit": "ball",
                "frequency": "daily",
                "slots": ["day"],
                "required": True,
            }
        ],
        "protocol_slugs": ["general_safety"],
    },
]
