"""initial schema

Revision ID: 9a613d12d76d
Revises: 
Create Date: 2026-08-18 18:50:14.588014
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9a613d12d76d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis_templates',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=48), nullable=False),
    sa.Column('name', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('specialty', sa.String(length=64), nullable=True),
    sa.Column('icd10', sa.String(length=16), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('checkin_questions', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('protocol_slugs', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_templates_code'), 'diagnosis_templates', ['code'], unique=True)
    op.create_index(op.f('ix_diagnosis_templates_specialty'), 'diagnosis_templates', ['specialty'], unique=False)
    op.create_table('protocols',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('specialty', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protocols_is_active'), 'protocols', ['is_active'], unique=False)
    op.create_index(op.f('ix_protocols_slug'), 'protocols', ['slug'], unique=True)
    op.create_index(op.f('ix_protocols_specialty'), 'protocols', ['specialty'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.Enum('patient', 'doctor', 'admin', name='user_role', native_enum=False, length=40), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_push_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_preferences', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ivr_reminders_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index('ix_users_role_active', 'users', ['role', 'is_active'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('actor_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_care_thread_id'), 'audit_logs', ['care_thread_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_table('auth_identities',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('provider', sa.Enum('phone', 'google', 'telegram', name='auth_provider', native_enum=False, length=40), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('raw_profile', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'subject', name='uq_auth_identity_provider_subject'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_auth_identity_user_provider')
    )
    op.create_index(op.f('ix_auth_identities_user_id'), 'auth_identities', ['user_id'], unique=False)
    op.create_table('care_threads',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('patient_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('doctor_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('kind', sa.Enum('doctor', 'personal', name='care_thread_kind', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='care_thread_status', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'personal' AND doctor_user_id IS NULL) OR (kind = 'doctor' AND doctor_user_id IS NOT NULL)", name='ck_care_thread_kind_matches_doctor'),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_user_id', 'doctor_user_id', name='uq_care_thread_pair')
    )
    op.create_index(op.f('ix_care_threads_doctor_user_id'), 'care_threads', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_care_threads_patient_user_id'), 'care_threads', ['patient_user_id'], unique=False)
    op.create_index('uq_care_thread_personal', 'care_threads', ['patient_user_id'], unique=True, postgresql_where=sa.text('doctor_user_id IS NULL'), sqlite_where=sa.text('doctor_user_id IS NULL'))
    op.create_table('device_tokens',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('platform', sa.Enum('android', 'ios', name='device_platform', native_enum=False, length=40), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('doctor_profiles',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('specialty', sa.String(length=64), nullable=False),
    sa.Column('experience_years', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('workplace', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.Enum('pending', 'approved', 'rejected', name='doctor_verification_status', native_enum=False, length=40), nullable=False),
    sa.Column('verification_note', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connect_code', sa.String(length=16), nullable=False),
    sa.Column('consultation_open', sa.Boolean(), nullable=False),
    sa.Column('consultation_specialties', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('consultation_price_uzs', sa.Integer(), nullable=True),
    sa.Column('rating_sum', sa.Integer(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('answered_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('consultation_price_uzs IS NULL OR consultation_price_uzs >= 0', name='ck_doctor_price_nonneg'),
    sa.CheckConstraint('experience_years >= 0', name='ck_doctor_experience_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_doctor_open_specialty', 'doctor_profiles', ['consultation_open', 'specialty'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_connect_code'), 'doctor_profiles', ['connect_code'], unique=True)
    op.create_index(op.f('ix_doctor_profiles_specialty'), 'doctor_profiles', ['specialty'], unique=False)
    op.create_index(op.f('ix_doctor_profiles_verification_status'), 'doctor_profiles', ['verification_status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('type', sa.Enum('patient_added', 'consultation_new', 'consultation_answered', 'consultation_refunded', 'medication_due', 'checkin_due', 'ai_escalation', 'diagnosis_pending', 'diagnosis_change_request', 'wallet_updated', 'weekly_report', 'doctor_replied', name='notification_type', native_enum=False, length=40), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pushed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('push_error', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key', name='uq_notification_dedupe')
    )
    op.create_index('ix_notification_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('otp_challenges',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('code_hash', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.Enum('login', 'link_phone', 'change_phone', name='otp_purpose', native_enum=False, length=40), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otp_challenges_phone'), 'otp_challenges', ['phone'], unique=False)
    op.create_index('ix_otp_phone_purpose_created', 'otp_challenges', ['phone', 'purpose', 'created_at'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.Column('region', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('payout_requests',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('amount_uzs', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('requested', 'processing', 'paid', 'rejected', name='payout_status', native_enum=False, length=40), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('card_holder', sa.String(length=160), nullable=True),
    sa.Column('destination_ref', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_uzs > 0', name='ck_payout_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payout_requests_status'), 'payout_requests', ['status'], unique=False)
    op.create_index(op.f('ix_payout_requests_user_id'), 'payout_requests', ['user_id'], unique=False)
    op.create_table('protocol_chunks',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('protocol_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('heading', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunk_protocol_locale', 'protocol_chunks', ['protocol_id', 'locale'], unique=False)
    op.create_index(op.f('ix_protocol_chunks_locale'), 'protocol_chunks', ['locale'], unique=False)
    op.create_index(op.f('ix_protocol_chunks_protocol_id'), 'protocol_chunks', ['protocol_id'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('replaced_by_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_sessions_token_hash'), 'refresh_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('wallets',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('balance_uzs', sa.Integer(), nullable=False),
    sa.Column('lifetime_earned_uzs', sa.Integer(), nullable=False),
    sa.Column('lifetime_paid_out_uzs', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('balance_uzs >= 0', name='ck_wallet_balance_nonneg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('ai_escalations',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('doctor_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('patient_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('ai_note', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=48), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_escalations_care_thread_id'), 'ai_escalations', ['care_thread_id'], unique=False)
    op.create_index(op.f('ix_ai_escalations_doctor_user_id'), 'ai_escalations', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_ai_escalations_is_open'), 'ai_escalations', ['is_open'], unique=False)
    op.create_table('checkin_submissions',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('slot', sa.String(length=24), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('care_thread_id', 'local_date', 'slot', name='uq_checkin_thread_slot')
    )
    op.create_index(op.f('ix_checkin_submissions_care_thread_id'), 'checkin_submissions', ['care_thread_id'], unique=False)
    op.create_index(op.f('ix_checkin_submissions_local_date'), 'checkin_submissions', ['local_date'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('patient_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('doctor_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('targeting', sa.Enum('direct', 'matched', name='consultation_targeting', native_enum=False, length=40), nullable=False),
    sa.Column('specialty', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'pending_payment', 'open', 'claimed', 'answered', 'rated', 'refunded', 'cancelled', name='consultation_status', native_enum=False, length=40), nullable=False),
    sa.Column('price_uzs', sa.Integer(), nullable=False),
    sa.Column('platform_fee_uzs', sa.Integer(), nullable=False),
    sa.Column('doctor_earning_uzs', sa.Integer(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attachments', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('price_uzs >= 0', name='ck_consultation_price_nonneg'),
    sa.CheckConstraint('rating IS NULL OR (rating >= 1 AND rating <= 5)', name='ck_consultation_rating_range'),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_consultation_open_specialty', 'consultations', ['status', 'specialty'], unique=False)
    op.create_index(op.f('ix_consultations_doctor_user_id'), 'consultations', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_consultations_patient_user_id'), 'consultations', ['patient_user_id'], unique=False)
    op.create_index(op.f('ix_consultations_sla_expires_at'), 'consultations', ['sla_expires_at'], unique=False)
    op.create_index(op.f('ix_consultations_specialty'), 'consultations', ['specialty'], unique=False)
    op.create_index(op.f('ix_consultations_status'), 'consultations', ['status'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('template_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('status', sa.Enum('unverified', 'verified', name='diagnosis_status', native_enum=False, length=40), nullable=False),
    sa.Column('created_by_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['diagnosis_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_care_thread_id'), 'diagnoses', ['care_thread_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_status'), 'diagnoses', ['status'], unique=False)
    op.create_table('doctor_subscriptions',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('doctor_profile_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('plan', sa.Enum('monthly', 'yearly', name='subscription_plan', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('trial', 'active', 'expired', 'cancelled', name='subscription_status', native_enum=False, length=40), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_profile_id'], ['doctor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_profile_id')
    )
    op.create_index(op.f('ix_doctor_subscriptions_status'), 'doctor_subscriptions', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('owner_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_documents_care_thread_id'), 'documents', ['care_thread_id'], unique=False)
    op.create_index(op.f('ix_documents_owner_user_id'), 'documents', ['owner_user_id'], unique=False)
    op.create_table('medications',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('dose', sa.String(length=80), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('times', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('weekdays', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_medications_care_thread_id'), 'medications', ['care_thread_id'], unique=False)
    op.create_index(op.f('ix_medications_is_active'), 'medications', ['is_active'], unique=False)
    op.create_table('metric_series',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('key', sa.String(length=48), nullable=False),
    sa.Column('label', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('target_min', sa.Float(), nullable=True),
    sa.Column('target_max', sa.Float(), nullable=True),
    sa.Column('critical_min', sa.Float(), nullable=True),
    sa.Column('critical_max', sa.Float(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=False),
    sa.Column('chart_type', sa.String(length=16), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_template_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_template_id'], ['diagnosis_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('care_thread_id', 'key', name='uq_series_thread_key')
    )
    op.create_index(op.f('ix_metric_series_care_thread_id'), 'metric_series', ['care_thread_id'], unique=False)
    op.create_table('patient_invites',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('doctor_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('diagnosis_text', sa.Text(), nullable=True),
    sa.Column('template_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('status', sa.Enum('issued', 'redeemed', 'expired', 'revoked', name='invite_status', native_enum=False, length=40), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('redeemed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('redeemed_by_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('document_ids', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['doctor_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['redeemed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['diagnosis_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_invites_code'), 'patient_invites', ['code'], unique=True)
    op.create_index(op.f('ix_patient_invites_doctor_user_id'), 'patient_invites', ['doctor_user_id'], unique=False)
    op.create_index(op.f('ix_patient_invites_phone'), 'patient_invites', ['phone'], unique=False)
    op.create_table('weekly_reports',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('care_thread_id', 'period_start', name='uq_weekly_report_period')
    )
    op.create_index(op.f('ix_weekly_reports_care_thread_id'), 'weekly_reports', ['care_thread_id'], unique=False)
    op.create_table('ai_messages',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('role', sa.Enum('patient', 'assistant', 'doctor', 'system', name='message_role', native_enum=False, length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('outcome', sa.Enum('answered', 'escalated', 'no_doctor', 'emergency', 'refused', name='ai_outcome', native_enum=False, length=40), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('escalation_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escalation_id'], ['ai_escalations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_message_thread_created', 'ai_messages', ['care_thread_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_care_thread_id'), 'ai_messages', ['care_thread_id'], unique=False)
    op.create_table('diagnosis_change_requests',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('diagnosis_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('requested_by_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='change_request_status', native_enum=False, length=40), nullable=False),
    sa.Column('resolved_by_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_change_requests_diagnosis_id'), 'diagnosis_change_requests', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_change_requests_status'), 'diagnosis_change_requests', ['status'], unique=False)
    op.create_table('medication_doses',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('medication_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'taken', 'missed', 'skipped', name='dose_status', native_enum=False, length=40), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_via', sa.Enum('app', 'ivr', 'doctor', name='dose_confirmation_channel', native_enum=False, length=40), nullable=True),
    sa.Column('push_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('call_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_id', 'scheduled_at', name='uq_dose_medication_slot')
    )
    op.create_index('ix_dose_status_scheduled', 'medication_doses', ['status', 'scheduled_at'], unique=False)
    op.create_index(op.f('ix_medication_doses_care_thread_id'), 'medication_doses', ['care_thread_id'], unique=False)
    op.create_index(op.f('ix_medication_doses_medication_id'), 'medication_doses', ['medication_id'], unique=False)
    op.create_index(op.f('ix_medication_doses_scheduled_at'), 'medication_doses', ['scheduled_at'], unique=False)
    op.create_table('metric_readings',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('series_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('value_secondary', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('patient', 'doctor', 'import', 'device', name='reading_source', native_enum=False, length=40), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_by_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['metric_series.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metric_readings_care_thread_id'), 'metric_readings', ['care_thread_id'], unique=False)
    op.create_index(op.f('ix_metric_readings_recorded_at'), 'metric_readings', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_metric_readings_series_id'), 'metric_readings', ['series_id'], unique=False)
    op.create_index('ix_reading_series_recorded', 'metric_readings', ['series_id', 'recorded_at'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('provider', sa.Enum('click', 'payme', name='payment_provider', native_enum=False, length=40), nullable=False),
    sa.Column('purpose', sa.Enum('consultation', 'subscription', name='payment_purpose', native_enum=False, length=40), nullable=False),
    sa.Column('status', sa.Enum('created', 'pending', 'paid', 'cancelled', 'refunded', 'failed', name='payment_status', native_enum=False, length=40), nullable=False),
    sa.Column('amount_uzs', sa.Integer(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('consultation_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('subscription_plan', sa.String(length=16), nullable=True),
    sa.Column('provider_transaction_id', sa.String(length=128), nullable=True),
    sa.Column('provider_state', sa.String(length=32), nullable=True),
    sa.Column('provider_payload', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('prepared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_uzs >= 0', name='ck_payment_amount_nonneg'),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_transaction_id', name='uq_payment_provider_txn')
    )
    op.create_index(op.f('ix_payments_consultation_id'), 'payments', ['consultation_id'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('thread_messages',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('care_thread_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('sender_user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('role', sa.Enum('patient', 'assistant', 'doctor', 'system', name='message_role', native_enum=False, length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('escalation_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['care_thread_id'], ['care_threads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['escalation_id'], ['ai_escalations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thread_messages_care_thread_id'), 'thread_messages', ['care_thread_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('wallet_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('type', sa.Enum('consultation_earning', 'payout', 'adjustment', 'reversal', name='wallet_txn_type', native_enum=False, length=40), nullable=False),
    sa.Column('amount_uzs', sa.Integer(), nullable=False),
    sa.Column('balance_after_uzs', sa.Integer(), nullable=False),
    sa.Column('consultation_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('payout_request_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['consultation_id'], ['consultations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payout_request_id'], ['payout_requests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_wallet_txn_idempotency')
    )
    op.create_index(op.f('ix_wallet_transactions_wallet_id'), 'wallet_transactions', ['wallet_id'], unique=False)
    op.create_table('reminder_calls',
    sa.Column('id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('dose_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.String(length=36), 'sqlite'), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('provider_call_id', sa.String(length=128), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('digits', sa.String(length=8), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dose_id'], ['medication_doses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dose_id', name='uq_reminder_call_dose')
    )
    op.create_index(op.f('ix_reminder_calls_provider_call_id'), 'reminder_calls', ['provider_call_id'], unique=False)
    op.create_index(op.f('ix_reminder_calls_user_id'), 'reminder_calls', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_calls_user_id'), table_name='reminder_calls')
    op.drop_index(op.f('ix_reminder_calls_provider_call_id'), table_name='reminder_calls')
    op.drop_table('reminder_calls')
    op.drop_index(op.f('ix_wallet_transactions_wallet_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_thread_messages_care_thread_id'), table_name='thread_messages')
    op.drop_table('thread_messages')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_consultation_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_reading_series_recorded', table_name='metric_readings')
    op.drop_index(op.f('ix_metric_readings_series_id'), table_name='metric_readings')
    op.drop_index(op.f('ix_metric_readings_recorded_at'), table_name='metric_readings')
    op.drop_index(op.f('ix_metric_readings_care_thread_id'), table_name='metric_readings')
    op.drop_table('metric_readings')
    op.drop_index(op.f('ix_medication_doses_scheduled_at'), table_name='medication_doses')
    op.drop_index(op.f('ix_medication_doses_medication_id'), table_name='medication_doses')
    op.drop_index(op.f('ix_medication_doses_care_thread_id'), table_name='medication_doses')
    op.drop_index('ix_dose_status_scheduled', table_name='medication_doses')
    op.drop_table('medication_doses')
    op.drop_index(op.f('ix_diagnosis_change_requests_status'), table_name='diagnosis_change_requests')
    op.drop_index(op.f('ix_diagnosis_change_requests_diagnosis_id'), table_name='diagnosis_change_requests')
    op.drop_table('diagnosis_change_requests')
    op.drop_index(op.f('ix_ai_messages_care_thread_id'), table_name='ai_messages')
    op.drop_index('ix_ai_message_thread_created', table_name='ai_messages')
    op.drop_table('ai_messages')
    op.drop_index(op.f('ix_weekly_reports_care_thread_id'), table_name='weekly_reports')
    op.drop_table('weekly_reports')
    op.drop_index(op.f('ix_patient_invites_phone'), table_name='patient_invites')
    op.drop_index(op.f('ix_patient_invites_doctor_user_id'), table_name='patient_invites')
    op.drop_index(op.f('ix_patient_invites_code'), table_name='patient_invites')
    op.drop_table('patient_invites')
    op.drop_index(op.f('ix_metric_series_care_thread_id'), table_name='metric_series')
    op.drop_table('metric_series')
    op.drop_index(op.f('ix_medications_is_active'), table_name='medications')
    op.drop_index(op.f('ix_medications_care_thread_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_documents_owner_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_care_thread_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_doctor_subscriptions_status'), table_name='doctor_subscriptions')
    op.drop_table('doctor_subscriptions')
    op.drop_index(op.f('ix_diagnoses_status'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_care_thread_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_consultations_status'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_specialty'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_sla_expires_at'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_patient_user_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_doctor_user_id'), table_name='consultations')
    op.drop_index('ix_consultation_open_specialty', table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_checkin_submissions_local_date'), table_name='checkin_submissions')
    op.drop_index(op.f('ix_checkin_submissions_care_thread_id'), table_name='checkin_submissions')
    op.drop_table('checkin_submissions')
    op.drop_index(op.f('ix_ai_escalations_is_open'), table_name='ai_escalations')
    op.drop_index(op.f('ix_ai_escalations_doctor_user_id'), table_name='ai_escalations')
    op.drop_index(op.f('ix_ai_escalations_care_thread_id'), table_name='ai_escalations')
    op.drop_table('ai_escalations')
    op.drop_table('wallets')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index(op.f('ix_refresh_sessions_token_hash'), table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index(op.f('ix_protocol_chunks_protocol_id'), table_name='protocol_chunks')
    op.drop_index(op.f('ix_protocol_chunks_locale'), table_name='protocol_chunks')
    op.drop_index('ix_chunk_protocol_locale', table_name='protocol_chunks')
    op.drop_table('protocol_chunks')
    op.drop_index(op.f('ix_payout_requests_user_id'), table_name='payout_requests')
    op.drop_index(op.f('ix_payout_requests_status'), table_name='payout_requests')
    op.drop_table('payout_requests')
    op.drop_table('patient_profiles')
    op.drop_index('ix_otp_phone_purpose_created', table_name='otp_challenges')
    op.drop_index(op.f('ix_otp_challenges_phone'), table_name='otp_challenges')
    op.drop_table('otp_challenges')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index('ix_notification_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_doctor_profiles_verification_status'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_specialty'), table_name='doctor_profiles')
    op.drop_index(op.f('ix_doctor_profiles_connect_code'), table_name='doctor_profiles')
    op.drop_index('ix_doctor_open_specialty', table_name='doctor_profiles')
    op.drop_table('doctor_profiles')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index('uq_care_thread_personal', table_name='care_threads', postgresql_where=sa.text('doctor_user_id IS NULL'), sqlite_where=sa.text('doctor_user_id IS NULL'))
    op.drop_index(op.f('ix_care_threads_patient_user_id'), table_name='care_threads')
    op.drop_index(op.f('ix_care_threads_doctor_user_id'), table_name='care_threads')
    op.drop_table('care_threads')
    op.drop_index(op.f('ix_auth_identities_user_id'), table_name='auth_identities')
    op.drop_table('auth_identities')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_care_thread_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_role_active', table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_protocols_specialty'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_slug'), table_name='protocols')
    op.drop_index(op.f('ix_protocols_is_active'), table_name='protocols')
    op.drop_table('protocols')
    op.drop_index(op.f('ix_diagnosis_templates_specialty'), table_name='diagnosis_templates')
    op.drop_index(op.f('ix_diagnosis_templates_code'), table_name='diagnosis_templates')
    op.drop_table('diagnosis_templates')
    # ### end Alembic commands ###
